import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { ToastContainer } from "react-toastify";

const poppins= Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400',"500","600","700"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
       className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full bg-[#081221] flex flex-col">
        <Navbar></Navbar>
        <main>
          {children}
        </main>
        <Footer></Footer>
         <ToastContainer />
        </body>
    </html>
  );
}
